/*
 * ImperialMarch.h
 *
 *  Created on: 22/03/2014
 *      Author: xavier
 */

#ifndef IMPERIALMARCH_H_
#define IMPERIALMARCH_H_

#include "Notes.h"

SNotes partiture [] = {
		{SOL3, NORMAL},
		{SOL3, NORMAL},
		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SI3, QUARTER},

		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SI3, QUARTER},
		{SOL3, DOUBLE},

		{RE4, NORMAL},
		{RE4, NORMAL},
		{RE4, NORMAL},
		{MI4, HALF+QUARTER},
		{SI3, QUARTER},

		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SI3, QUARTER},
		{SOL3, DOUBLE},

		{SOL4, NORMAL},
		{SOL3, HALF+QUARTER},
		{SOL3, QUARTER},
		{SOL4, NORMAL},
		{FA4_, HALF+QUARTER},
		{FA4, QUARTER},

		{MI4, QUARTER},
		{RE4_, QUARTER},
		{MI4, HALF},
		{REST, OCTAVE},
		{SOL3_, HALF},
		{DO4_, NORMAL},
		{DO4, HALF+QUARTER},
		{SI3, QUARTER},

		{SI3, QUARTER},
		{LA3, QUARTER},
		{SI3, HALF},
		{REST, OCTAVE},
		{MI3, HALF},
		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SOL3, QUARTER},

		{SI3, NORMAL},
		{SOL3, HALF+QUARTER},
		{SI3, QUARTER},
		{RE4, DOUBLE},
		{SOL4, NORMAL},
		{SOL3, HALF+QUARTER},
		{SOL3, QUARTER},
		{SOL4, NORMAL},
		{FA4_, HALF+QUARTER},
		{FA4, QUARTER},
		{MI4, QUARTER},
		{RE4_, QUARTER},
		{MI4, HALF},
		{REST, OCTAVE},
		{SOL3_, HALF},
		{DO4_, NORMAL},
		{DO4, HALF+QUARTER},
		{SI3, QUARTER},

		{SI3, QUARTER},
		{LA3, QUARTER},
		{SI3, HALF},
		{REST, OCTAVE},
		{MI3, HALF},
		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SI3, QUARTER},

		{SOL3, NORMAL},
		{MI3, HALF+QUARTER},
		{SI3, QUARTER},
		{SOL3, DOUBLE},

		{REST, 5000},
		{0, 0},
};



#endif /* IMPERIALMARCH_H_ */
